### PR TITLE
separating core from the updater

### PR DESCRIPTION
**Pull request by ananyasaxena**
lets people require a lighter version of the code `require('useragent/core')`

### CODE REVIEW

**Comment by 3rd-Eden** [comment]
I'm fine with the additional separation between the 2, but I don't think we need to start bundling lodash with it.

**Comment by 3rd-Eden** [comment]
TY

**Comment by jainvijay** [comment]
Hey @3rd-Eden ,

Is it possible to get the latest package with these changes as on npm the latest is still the an old package.

npmjs.com/package/useragent

**Comment by 3rd-Eden** [comment]
it's in 2.2.0

**Comment by 3rd-Eden** [comment]
Reverted, breaks a shit ton of important features.

**Pull request merged**
